# Generated by Django 4.2.3 on 2023-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('year_of_issue', models.DateField()),
                ('amount_of_ram', models.PositiveSmallIntegerField()),
                ('hd_capacity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('quantity_in_stock', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Notebook_info',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
