# Generated by Django 4.2.3 on 2023-10-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_notebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebook',
            new_name='Laptop',
        ),
        migrations.AlterModelTable(
            name='laptop',
            table='Laptop_info',
        ),
    ]
